version: "3.2"
services:
  php:
    build: "./php/"
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: "./apache/"
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mariadb
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=khaldrogo
    volumes:
      - ./mysqlData/:/home/mysqlData
      - ./mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: khaldrogo
      POSTGRES_DB: test_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: khaldrogo
    networks:
      - backend
      - frontend
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - ./workbenchconf:/config
    ports:
      - 8083:3000
    cap_add:
      - IPC_LOCK
    networks: 
      - backend
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

networks:
  frontend:
  backend:
  postgres:

volumes:
    postgres:
    pgadmin:
